### ISSUE TITLE
How to use it

### ISSUE THREAD

**Issue by dilawar** [ajkswamy/BlenderSWCVizualizer#1]
Hi,

I just installed blender `apt-get install blender`. When I run the script, it complains about missing module `bpy`. I assume that this is blender python scripting module. 

I am not sure if installing blender also installs this python module. Can you suggest which package to install to get this module. `pip install bpy` didn't help.

**Comment by ajkswamy** [comment]
Hello

Please take a look at the Readme file about running the scripts and follow the steps outlined there. I will try to explain again. Basically, you need to do the following:
1. Tell the blender python interpreter where to find 'blenderHelper.py'. This is done in the first two lines of all the scripts by adding the path containing 'blenderHelpder.py' to sys.path. Change this path which needs to be added appropriately in the scripts.
2. Next you need to tell the scripts which SWC file(s) to use. This is done using 
        (a) the 'swcs' list in compareNrnBlender.py and vizSSWCMultiple.py or
        (b) the fifth argument in "blender --python <script.py> -- /path/to/SWC/file" for the other scripts.
   Change the list 'swcs' to contain the paths of the SWCs that you want of visualize.
3. Open a terminal. Make sure the blender executable has been added to PATH (check by typing 'blender'). Then execute one of the scripts using:
     (a) blender --python vizSWC.py -- /path/to/SWC/file
     (b) blender --python compareNrnsBlender.py
     (c) blender --python vizSSWC.py -- /path/to/SWC/file
     (d) blender --python vizSSWC_schematic.py -- /path/to/SWC/file
     (e) blender --python vizSSWCMultiple.py
   In (a), (c) and (d) replace '/path/to/SWC/file' with the path to the SWC file you want to visualize. 
   NOTE: do not forget the "--"(double minus signs) and the spaces before and after it in (a), (c) and (d) above.
